// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_0q9FGmNkNB95PqjIVplvAcq8UDs8H1U',
    appId: '1:267162092585:web:e0d4fcd9ee167808d48838',
    messagingSenderId: '267162092585',
    projectId: 'beauteek-b595e',
    authDomain: 'beauteek-b595e.firebaseapp.com',
    storageBucket: 'beauteek-b595e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUHhnwUy7XKUpHFe2V2iz1-uvzPK9U1-8',
    appId: '1:267162092585:android:7f8aad72af422f83d48838',
    messagingSenderId: '267162092585',
    projectId: 'beauteek-b595e',
    storageBucket: 'beauteek-b595e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8JHl1RNnimX4eDSLqfPhZBONGuJe8Cbs',
    appId: '1:267162092585:ios:d5ffbe0b8b8aedd5d48838',
    messagingSenderId: '267162092585',
    projectId: 'beauteek-b595e',
    storageBucket: 'beauteek-b595e.firebasestorage.app',
    iosClientId: '267162092585-6is70vegr5cnsmmn6p5v733mrip44uq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8JHl1RNnimX4eDSLqfPhZBONGuJe8Cbs',
    appId: '1:267162092585:ios:d5ffbe0b8b8aedd5d48838',
    messagingSenderId: '267162092585',
    projectId: 'beauteek-b595e',
    storageBucket: 'beauteek-b595e.firebasestorage.app',
    iosClientId: '267162092585-6is70vegr5cnsmmn6p5v733mrip44uq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_0q9FGmNkNB95PqjIVplvAcq8UDs8H1U',
    appId: '1:267162092585:web:626e38905a0a674ed48838',
    messagingSenderId: '267162092585',
    projectId: 'beauteek-b595e',
    authDomain: 'beauteek-b595e.firebaseapp.com',
    storageBucket: 'beauteek-b595e.firebasestorage.app',
  );
}
